# Netlify 빌드 및 함수 설정
[build]
  # 이 프로젝트는 정적 HTML 파일과 함수로만 이루어져 있으므로
  # 별도의 빌드 명령이 필요 없습니다.
  command = "npm install"
  # 배포할 폴더를 public으로 지정합니다.
  publish = "."
  # 서버리스 함수가 위치한 폴더를 지정합니다.
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
